CREATE TABLE PROFILES
(
	ID INTEGER NOT NULL AUTO_INCREMENT, 
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PROFILE PRIMARY KEY(ID)
);

CREATE TABLE USERS
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL, 
    CONSTRAINT PK_USER PRIMARY KEY(ID)
);

CREATE TABLE USERPROFILES
(
	ID INTEGER NOT NULL AUTO_INCREMENT,
    USERID INTEGER NOT NULL,
    PROFILEID INTEGER NOT NULL,
    CONFIGURATION TEXT NOT NULL,
    CONSTRAINT PK_USERPROFILE PRIMARY KEY(ID),
    CONSTRAINT FK_USER_UPROFILE FOREIGN KEY(USERID) REFERENCES USERS(ID),
    CONSTRAINT FK_PROFILE_UPROFILE FOREIGN KEY(PROFILEID) REFERENCES PROFILES(ID)
)