CREATE TABLE PROFILE
(
	ID INTEGER NOT NULL, 
    NAME VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PROFILE PRIMARY KEY(ID)
);

CREATE TABLE USER
(
	ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL, 
    CONSTRAINT PK_USER PRIMARY KEY(ID)
);

CREATE TABLE USERPROFILE
(
	ID INTEGER NOT NULL,
    USERID INTEGER NOT NULL,
    PROFILEID INTEGER NOT NULL,
    CONFIGURATION TEXT NOT NULL,
    CONSTRAINT PK_USERPROFILE PRIMARY KEY(ID),
    CONSTRAINT FK_USER_UPROFILE FOREIGN KEY(USERID) REFERENCES USER(ID),
    CONSTRAINT FK_PROFILE_UPROFILE FOREIGN KEY(PROFILEID) REFERENCES PROFILE(ID)
);


